#! /usr/bin/env bash
#http://wiki.gridcoin.us/Linux_Downloads_(pre-compiled)
echo "Would you like to install gridcoin and boinc or just boinc?(g&b/b)"
read DECESION
if [[ $DECESION == "g&b" ]]
then
	sudo add-apt-repository ppa:gridcoin/gridcoin-stable
	sudo apt-get update
	sudo apt-get upgrade
	sudo ufw allow 32749/tcp
	sudo apt-get install -y boinc-client
	sudo apt-get install -y boinc-manager
	sudo apt-get install -y gridcoinresearch-qt
	sudo apt-get install -y gridcoinresearchd
        sudo apt-get install -y virtualbox
	sudo apt-get install -y unzip
	sudo apt-get autoremove
	sudo apt-get clean
	cd ~/Downloads
	wget http://download.gridcoin.us/download/downloadstake/signed/snapshot.zip
	unzip -o snapshot.zip -d ~/.GridcoinResearch
	rm snapshot.zip
	mkdir ~/.BOINC
	touch ~/.BOINC/mine_gridcoin
	echo '#! /usr/bin/env bash
#This file makes sure that gridcoin is running on the computer.
while true 
do
        sleep 90
        if [[ $(pgrep "gridcoinresearch*") != "" ]]
        then
                cd $(pwd)
        else
                /usr/bin/gridcoinresearch </dev/null &>/dev/null &
        fi
done' >> ~/.BOINC/mine_gridcoin
	sudo chmod +x ~/.BOINC/mine_gridcoin
	mkdir ~/.config
	mkdir ~/.config/autostart
	echo "[Desktop Entry]
Type=Application
Exec=~/.BOINC/mine_gridcoin
Hidden=false
NoDisplay=false
X-GNOME-Autostart-enabled=true
Name[en_US]=Gridcoin Mining
Name=Gridcoin
Comment[en_US]=Mine Gridcoin 
Comment=Mine Gridcoin" >> /home/$(whoami)/.config/autostart/mine.desktop
else
	sudo apt-get update
	sudo apt-get upgrade
	sudo apt-get install -y boinc-client
	sudo apt-get install -y boinc-manager
        sudo apt-get install -y virtualbox
	sudo apt-get autoremove
	sudo apt-get clean
fi
