#! /usr/bin/env bash
sudo add-apt-repository -y ppa:webupd8team/java
sudo add-apt-repository -y ppa:team-xbmc/ppa
sudo add-apt-repository -y ppa:webupd8team/y-ppa-manager
sudo add-apt-repository -y ppa:freecad-maintainers/freecad-stable
sudo add-apt-repository -y ppa:otto-kesselgulasch/gimp
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get install -y wine
sudo apt-get install -y oracle-java8-installer
sudo apt-get install -y vlc
sudo apt-get install -y android-tools-adb
sudo apt-get install -y android-tools-fastboot
sudo apt-get install -y audacity
sudo apt-get install -y python-software-properties
sudo apt-get install -y synaptic
sudo apt-get install -y libreoffice
sudo apt-get install -y flashplugin-installer
sudo apt-get install -y filezilla 
sudo apt-get install -y virtualbox
sudo apt-get install -y virtualbox-guest-additions-iso
sudo apt-get install -y virtualbox-guest-utils
sudo apt-get install -y exfat-fuse 
sudo apt-get install -y exfat-utils
sudo apt-get install -y freecad
sudo apt-get install -y git
sudo apt-get install -y libtext-csv-perl
sudo apt-get install -y python3-pip
sudo apt-get install -y python3-pyqt4 
sudo apt-get install -y pyqt4-dev-tools
sudo apt-get install -y inkscape 
sudo apt-get install -y qt4-designer
sudo apt-get install -y gimp
sudo apt-get install -y arduino

